# Generated by Django 3.0.8 on 2020-08-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='species',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='species',
            name='fact',
            field=models.TextField(blank=True, default=''),
        ),
    ]
